# Generated by Django 2.1.2 on 2019-03-07 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlackList', '0002_auto_20190307_1222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='data',
            new_name='date',
        ),
    ]
