# Generated by Django 2.1.2 on 2019-03-07 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlackList', '0004_offenders'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Offenders',
            new_name='Offender',
        ),
    ]
